# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task -a
    silent: true
  gen-parser:
    cmds:
      - task: antlr4-cmd
        vars:
          ARGS: -Dlanguage=Go -visitor -o gen *.g4
  clean-parser:
    dir: parser/
    cmds:
      - rm -rf .antlr
      - rm -rf gen/*
  test:
    cmds:
      - go test ./...
  prepare-grun:
    dir: parser/
    cmds:
      - task: antlr4-cmd
        vars:
          ARGS: PCRE.g4
      - javac *.java
  grun:
    dir: parser/
    cmds:
      - task: grun-cmd
        vars:
          ARGS: PCRE pcre -tree
    deps:
      - task: prepare-grun
  clean-grun:
    dir: parser/
    cmds:
      - rm *.java *.class *.tokens *.interp
  test-cmd:
    cmds:
      - go run main.go "a" "a|b|c"
      - go run main.go "aaaaabaaaaa" "(.*)b(?=aaaaa)\1"
      - go run main.go "aacaa" "(?=(a*b*))aac\1"
      - go run main.go -e=true "aaa" "\1aaa"
      - go run main.go "aaa" "\1aaa"
      - go run main.go "aaaaaa" "a*"
      - go run main.go "" "a*"
      - go run main.go "b" "a*"
      - go run main.go "a" "a+"
      - go run main.go "aaa" "a+"
      - go run main.go "" "a+"
      - go run main.go "" "a{3}"
      - go run main.go "aaa" "a{3}"
      - go run main.go "aaaaa" "a{3}"
      - go run main.go "aa" "a{3,}"
      - go run main.go "aaa" "a{3,}"
      - go run main.go "aaaaa" "a{3,}"
      - go run main.go "a" "a{2,4}"
      - go run main.go "aa" "a{2,4}"
      - go run main.go "aaa" "a{2,4}"
      - go run main.go "aaaa" "a{2,4}"
      - go run main.go "aaaaa" "a{2,4}"
      - go run main.go "aaaaa" "a{2,10}"
  
  # internals
  antlr4-cmd:
    dir: parser
    internal: true
    cmds:
      - java -Xmx500M -cp "/usr/local/lib/antlr-4.13.1-complete.jar:$CLASSPATH" org.antlr.v4.Tool {{.ARGS}}
  grun-cmd:
    dir: parser
    internal: true
    cmds:
      - java -Xmx500M -cp "/usr/local/lib/antlr-4.13.1-complete.jar:$CLASSPATH" org.antlr.v4.gui.TestRig {{.ARGS}}
    
